spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys-log?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: 192.168.10.17
    port: 5672
    username: root
    password: 123456
    publisher-confirms: true
    virtual-host: /

server:
  port: 9997